# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gsi.utils


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            bases=(gsi.utils.UnicodeNameMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name='mergecsv',
            options={'verbose_name_plural': 'MergeCSV cards'},
        ),
        migrations.AlterModelOptions(
            name='rftrain',
            options={'verbose_name_plural': 'RFTRain cards'},
        ),
        migrations.AlterUniqueTogether(
            name='carditem',
            unique_together=set([('content_type', 'object_id')]),
        ),
    ]
