"""
Django settings for GSI project.

Generated by 'django-admin startproject' using Django 1.8.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '+ht!6=9x07@-1v9p8&f9x2v19d57cja_4g!k%nrjnwo34j8cj+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

CRISPY_TEMPLATE_PACK = 'bootstrap3'

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'


PHP_CGI = '/usr/bin/php-cgi'

ADMINS = (
    ('Grigoriy Tsarik', 'artgrem@gmail.com')
)

# Application definition
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'solo',
    'registration',
    'crispy_forms',
    'django_php',
    'rest_framework.authtoken',

    'ckeditor',
    'ckeditor_uploader',

    'cards',
    'gsi',
    'customers',
    'log',
    'tags',
    'articles',
    'api',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

FILE_UPLOAD_HANDLERS = (
    'django.core.files.uploadhandler.MemoryFileUploadHandler',
    'django.core.files.uploadhandler.TemporaryFileUploadHandler',
)

FILE_UPLOAD_MAX_MEMORY_SIZE = 7864320

# FILE_UPLOAD_TEMP_DIR = os.path.join(BASE_DIR, "tmp")

ROOT_URLCONF = 'gsi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'), ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'gsi.context_processors.get_current_year',
            ],
        },
    },
]

WSGI_APPLICATION = 'gsi.wsgi.application'

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
STATICFILES_FINDERS = ("django.contrib.staticfiles.finders.FileSystemFinder",
                       "django.contrib.staticfiles.finders.AppDirectoriesFinder")
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
)

STATIC_ROOT = os.path.join(BASE_DIR, "collected_static/")
STATIC_DIR = STATICFILES_DIRS[0]
STATIC_URL = '/static/'

DEBUG_TOOLBAR_PATCH_SETTINGS = True
ENABLE_DEBUG_TOOLBAR = False

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# django rest framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_METADATA_CLASS': 'rest_framework.metadata.SimpleMetadata',
    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'DEFAULT_PAGINATION_CLASS': 'api.pagination.CustomPagination',
    'PAGE_SIZE': 10,
    # 'PAGINATE_BY_PARAM': 'page_size',
    'PAGINATE_BY': 1000,

    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler'

    # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    # 'PAGE_SIZE': 100,
    # 'MAX_PAGINATE_BY': 1000,

    # 'PAGINATE_BY_PARAM': 'page_size',
    # 'MAX_PAGINATE_BY': 500,
    # 'DEFAULT_RENDERER_CLASSES': (
    #     'rest_framework.renderers.UnicodeJSONRenderer',
    #     'rest_framework.renderers.BrowsableAPIRenderer',
    #     'rest_framework.renderers.XMLRenderer',
    #     'rest_framework.renderers.YAMLRenderer',
    # )
}

# REST_FRAMEWORK
# REST_FRAMEWORK = {
#     'DEFAULT_PERMISSION_CLASSES': (
#         # 'rest_framework.permissions.IsAdminUser',
#         'rest_framework.authentication.BasicAuthentication',
#         'rest_framework.authentication.SessionAuthentication',
#     ),
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework.authentication.TokenAuthentication',
#     ),
#     'DEFAULT_METADATA_CLASS': 'rest_framework.metadata.SimpleMetadata',
#     # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
#     # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
#     # 'PAGINATE_BY': 2,
#     # 'PAGE_SIZE': 2
# }

# settings for django-registration-redux
REGISTRATION_OPEN = True
ACCOUNT_ACTIVATION_DAYS = 7
# LOGIN_REDIRECT_URL = '/index/'
# LOGIN_URL = '/login/'
# LOGOUT_URL = '/logout/'

LOGIN_URL = 'users:auth_login'
LOGOUT_URL = 'users:auth_logout'



# to send the activation code
# EMAIL_HOST = 'localhost'
# EMAIL_PORT = 1025
# EMAIL_HOST_USER = ''
# EMAIL_HOST_PASSWORD = ''
# EMAIL_USE_TLS = False
# DEFAULT_FROM_EMAIL = 'info@google.ru'

# mailgun settings
# EMAIL_USE_TLS = True
# EMAIL_HOST = 'smtp.mailgun.org'
# EMAIL_HOST_USER = 'postmaster@sandboxb0a57a3959a74e848bcdde911debdc02.mailgun.org'
# EMAIL_HOST_PASSWORD = 'b8eaad09132286b3742260a52dbcba6a'
# EMAIL_PORT = 587

# send email for forgot password
# EMAIL_USE_TLS = True
MAIL_USE_SSL = True
EMAIL_HOST = 'smtp.example.com'
EMAIL_PORT = 12333
EMAIL_HOST_USER = 'user@user.post.com'
EMAIL_HOST_PASSWORD = 'password'
DEFAULT_FROM_EMAIL = 'noreply@exemple.com'
EMAIL_BACKEND = 'smtp.backend'

# Logging settings for django projects
MAIN_FILE = os.path.join(BASE_DIR, "/home/gsi/logs/main.log")
MAIN_DEBUG_FILE = os.path.join(BASE_DIR, "/home/gsi/logs/main_debug.log")

MAIN_FILE = '/home/gsi/logs/main_gsi.log'
MAIN_DEBUG_FILE = '/home/gsi/logs/main_gsi_debug.log'

LOG_FILE = os.path.join(BASE_DIR, 'gsi.log')

# # Time Format
# TIME_FORMAT = (
#     '%H:%M:%S.%f',  # '14:30:59.000200'
# )

# Logging setting
LOGGING = {
    'version': 1,
    'disable_existing_loggers': True,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue'
        }
    },
    'formatters': {
        'main_formatter': {
            'format': '==============  %(levelname)s:%(name)s:::: %(message)s '
                      '(%(asctime)s; %(filename)s:%(lineno)d)',
            'datefmt': "%Y-%m-%d %H:%M:%S",
        },
    },
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        },
        'console': {
            'level': 'ERROR',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'main_formatter',
        },
        'production_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': MAIN_FILE,
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 7,
            'formatter': 'main_formatter',
            'filters': ['require_debug_false'],
        },
        'debug_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': MAIN_DEBUG_FILE,
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 7,
            'formatter': 'main_formatter',
            'filters': ['require_debug_true'],
        },
        'null': {
            "class": 'django.utils.log.NullHandler',
        }
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins', 'console'],
            'level': 'ERROR',
            'propagate': True,
        },
        'django': {
            'handlers': ['null', ],
        },
        'py.warnings': {
            'handlers': ['null', ],
        },
        '': {
            'handlers': ['console', 'production_file', 'debug_file'],
            'level': "DEBUG",
        },
    }
}

# FTP Path
FTP_PATH = '/lustre/w23/CUSTOMER_FTP_AREA'

# home folder for new cripts
# /lustre/home/i214/indy0-home/mattgsi/bin
# /lustre/home/i214/indy0-lustre/mattgsi/scripts/runs/R_1321/

# /lustre/home/i214/mattgsi/indy0-lustre/mattgsi/scripts/runs
# /lustre/home/i214/indy0-lustre/mattgsi/scripts/runs
# SCRIPTS_HOME = '/lustre/w23/mattgsi/'
SCRIPTS_HOME = '/lustre/home/i214/indy0-lustre/mattgsi/'

EXECUTE_FE_COMMAND = '/lustre/home/i214/indy0-home/mattgsi/bin/execute_FE_commmand'
FE_SUBMIT = '/lustre/home/i214/indy0-home/mattgsi/bin/nfe_submit'
# PATH_RUNS_SCRIPTS = '/lustre/w23/mattgsi/scripts/runs'
PATH_RUNS_SCRIPTS = '/lustre/home/i214/indy0-lustre/mattgsi/scripts/runs'
PROCESS_NUM = 10
CONFIGFILE_PATH = '$RF_AUXDATA_DIR/'

# number paginations
NUM_PAGINATIONS = 7

# number execute runs
EXEC_RUNS = 2000

# Google maps
GOOGLE_MAP_ZOOM = 20
DAFAULT_LAT = 63.817957
DAFAULT_LON = -151.147061

# results_directory
# RESULTS_DIRECTORY = '/lustre/w23/mattgsi/satdata/RF/Projects/'
# POLYGONS_DIRECTORY = '/lustre/w23/mattgsi/satdata/RF/Polygons/kml/'

# RESULTS_DIRECTORY = '/lustre/home/i214/indy0-lustre/w23/mattgsi/satdata/RF/Projects/'
# POLYGONS_DIRECTORY = '/lustre/home/i214/indy0-lustre/w23/mattgsi/satdata/RF/Polygons/kml'

# tif and png files path and folders
PNG_DIRECTORY = 'media/png'
PNG_PATH = os.path.join(BASE_DIR, PNG_DIRECTORY)
# PROJECTS_PATH = '/lustre/w23/mattgsi/satdata/RF/Projects'
PROJECTS_PATH = '/lustre/home/i214/indy0-lustre/w23/mattgsi/satdata/RF/Projects/'

# LUT Directory
# LUT_DIRECTORY = '/lustre/w23/mattgsi/satdata/RF/LUTHOME'
LUT_DIRECTORY = '/lustre/home/i214/indy0-lustre/w23/mattgsi/satdata/RF/LUTHOME/'

# Script TifPng
SCRIPT_TIFPNG = os.path.join(BASE_DIR, "static/scripts_c/TifPng")

# Script GetPolyInfo
SCRIPT_GETPOLYINFO = os.path.join(BASE_DIR, "static/scripts_c/GetPolyInfo")

# Script MSize
SCRIPT_MAXSIZE = os.path.join(BASE_DIR, "static/scripts_c/msize.sh")

# Script Remap
SCRIPT_REMAP = os.path.join(BASE_DIR, "static/scripts_c/Remap")

# ATTRIBUTE_CONFIG
ATTRIBUTE_CONFIG = ['ATTRIBUTE_CONFIG.txt', 'ATTRIBUTE_CONFIG']

# KML files
KML_DIRECTORY = 'media/kml'
KML_PATH = os.path.join(BASE_DIR, KML_DIRECTORY)

# Temporary dir
TMP_DIRECTORY = 'media/temp_files'
TMP_PATH = os.path.join(BASE_DIR, TMP_DIRECTORY)

# Legends dir
LEGENDS_DIRECTORY = 'media/legends'
LEGENDS_PATH = os.path.join(BASE_DIR, LEGENDS_DIRECTORY)


# Remap TIF dir
REMAP_DIRECTORY = 'media/remap_tif'
REMAP_PATH = os.path.join(BASE_DIR, REMAP_DIRECTORY)

# Attributes
ATTRIBUTES_NAME = ['Total Area', 'Area total']

# Statistic
STATISTICS = ['Max', 'Mean', 'Median', 'Min', 'LQ', 'UQ']

# Card Type
CARD_TYPE = {
    'rftrain': 'RFTrain',
    'mergecsv': 'MergeCSV',
    'preproc': 'PreProc',
    'collate': 'Collate',
    'yearfilter': 'YearFilter',
    'remap': 'Remap',
    'rfscore': 'RFScore',
    'qrf': 'QRF',
    'randomforest': 'RandomForest',
    'calcstats': 'CalcStats'
}

# COLOR_HEX_NAME = [
#     'Aqua', 'Blue', 'BlueViolet', 'Brown', 'BurlyWood',
#     'CadetBlue', 'Chartreuse', 'Chocolate', 'Coral', 'CornflowerBlue',
#     'Crimson', 'DarkBlue', 'DarkCyan', 'DarkGoldenRod', 'DarkGreen',
#     'DarkMagenta', 'DarkRed', 'DarkSlateGray', 'GoldenRod', 'HotPink',
#     'Indigo', 'LawnGreen', 'LightSeaGreen', 'LightSlateGray', 'OrangeRed'
# ]

# COLOR_HEX = [
#     '#00FFFF', '#0000FF', '#8A2BE2', '#A52A2A', '#DEB887',
#     '#5F9EA0', '#7FFF00', '#D2691E', '#FF7F50', '#6495ED',
#     '#DC143C', '#00008B', '#008B8B', '#B8860B', '#006400',
#     '#8B008B', '#8B0000', '#2F4F4F', '#DAA520', '#FF69B4',
#     '#4B0082', '#7CFC00', '#20B2AA', '#778899', '#FF4500'
# ]

COLOR_HEX_NAME = [
    'aqua', 'aquamarine', 'blue', 'blueviolet', 'brown',
    'burlywood', 'cadetblue', 'chartreuse', 'chocolate', 'coral',
    'cornflowerblue', 'crimson', 'cyan', 'darkblue', 'darkcyan',
    'darkgoldenrod', 'darkgray', 'darkgreen', 'darkgrey', 'darkkhaki',
    'darkmagenta', 'darkolivegreen', 'darkorchid', 'darkred', 'darksalmon',
    'darkseagreen', 'darkslateblue', 'darkslategray', 'darkslategrey', 'darkturquoise',
    'darkviolet', 'deeppink', 'deepskyblue', 'dimgray', 'dimgrey',
    'dodgerblue', 'firebrick', 'floralwhite', 'forestgreen', 'fuchsia',
    'gainsboro', 'ghostwhite', 'gold', 'goldenrod', 'gray',
    'green', 'greenyellow', 'honeydew', 'hotpink', 'indianred',
    'indigo', 'lawngreen', 'lightblue', 'lightcoral', 'lightgreen',
    'lightsalmon', 'lightseagreen', 'lightskyblue', 'lightslategray', 'lightsteelblue',
    'lime', 'limegreen', 'magenta', 'maroon', 'mediumaquamarine',
    'mediumblue', 'mediumorchid', 'mediumpurple', 'mediumseagreen', 'mediumslateblue',
    'mediumspringgreen', 'mediumturquoise', 'mediumvioletred', 'midnightblue', 'navy',
    'olive', 'olivedrab', 'orangered', 'orchid', 'palevioletred',
    'peru', 'plum', 'purple', 'red', 'rosybrown',
    'royalblue', 'saddlebrown', 'salmon', 'sandybrown', 'seagreen',
    'sienna', 'silver', 'skyblue', 'slateblue', 'slategray',
    'springgreen', 'steelblue', 'tan', 'teal', 'tomato',
    'turquoise', 'violet', 'yellow', 'yellowgreen'
]

COLOR_HEX = [
    'ffffff00', 'ffd4ff7f', 'ffff0000', 'ffe22b8a', 'ff2a2aa5',
    'ff87b8de', 'ffa09e5f', 'ff00ff7f', 'ff1e69d2', 'ff507fff',
    'ffed9564', 'ff3c14dc', 'ffffff00', 'ff8b0000', 'ff8b8b00',
    'ff0b86b8', 'ffa9a9a9', 'ff006400', 'ffa9a9a9', 'ff6bb7bd',
    'ff8b008b', 'ff2f6b55', 'ffcc3299', 'ff00008b', 'ff7a96e9',
    'ff8fbc8f', 'ff8b3d48', 'ff4f4f2f', 'ff4f4f2f', 'ffd1ce00',
    'ffd30094', 'ff9314ff', 'ffffbf00', 'ff696969', 'ff696969',
    'ffff901e', 'ff2222b2', 'fff0faff', 'ff228b22', 'ffff00ff',
    'ffdcdcdc', 'fffff8f8', 'ff00d7ff', 'ff20a5da', 'ff808080',
    'ff008000', 'ff2fffad', 'fff0fff0', 'ffb469ff', 'ff5c5ccd',
    'ff82004b', 'ff00fc7c', 'ffe6d8ad', 'ff8080f0', 'ff90ee90',
    'ff7aa0ff', 'ffaab220', 'ffface87', 'ff998877', 'ffdec4b0',
    'ff00ff00', 'ff32cd32', 'ffff00ff', 'ff000080', 'ffaacd66',
    'ffcd0000', 'ffd355ba', 'ffd87093', 'ff71b33c', 'ffee687b',
    'ff9afa00', 'ffccd148', 'ff8515c7', 'ff701919', 'ff800000',
    'ff008080', 'ff238e6b', 'ff0045ff', 'ffd670da', 'ff9370d8',
    'ff3f85cd', 'ffdda0dd', 'ff800080', 'ff0000ff', 'ff8f8fbc',
    'ffe16941', 'ff13458b', 'ff7280fa', 'ff60a4f4', 'ff578b2e',
    'ff2d52a0', 'ffc0c0c0', 'ffebce87', 'ffcd5a6a', 'ff908070',
    'ff7fff00', 'ffb48246', 'ff8cb4d2', 'ff808000', 'ff4763ff',
    'ffd0e040', 'ffee82ee', 'ff00ffff', 'ff32cd9a'
]

try:
    from settings_local import *
except ImportError:
    pass

if ENABLE_DEBUG_TOOLBAR:
    MIDDLEWARE_CLASSES = ('debug_toolbar.middleware.DebugToolbarMiddleware',) + MIDDLEWARE_CLASSES
    INSTALLED_APPS = INSTALLED_APPS + ('debug_toolbar',)
