# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import gsi.utils


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20151211_1122'),
        ('gsi', '0002_tiletype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('environment_override', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('cards', models.ManyToManyField(to='cards.CardItem')),
                ('environment_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gsi.VariablesGroup')),
            ],
            bases=(gsi.utils.UnicodeNameMixin, models.Model),
        ),
    ]
