# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 14:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gsi.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0002_auto_20151211_1122'),
        ('gsi', '0003_cardsequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('log_file_path', models.CharField(blank=True, max_length=300, null=True)),
                ('log_file', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
            bases=(gsi.utils.UnicodeNameMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[(b'created', b'Created'), (b'pending', b'Pending'), (b'running', b'Running'), (b'success', b'Success'), (b'fail', b'Fail')], default=b'created', max_length=100)),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gsi.Log')),
            ],
            bases=(gsi.utils.UnicodeNameMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RunBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('directory_path', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('card_sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsi.CardSequence')),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsi.Resolution')),
            ],
            bases=(gsi.utils.UnicodeNameMixin, models.Model),
        ),
        migrations.CreateModel(
            name='RunStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[(b'created', b'Created'), (b'pending', b'Pending'), (b'running', b'Running'), (b'success', b'Success'), (b'fail', b'Fail')], default=b'pending', max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('card_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.CardItem')),
                ('parent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsi.Run')),
            ],
            bases=(gsi.utils.UnicodeNameMixin, models.Model),
        ),
        migrations.AddField(
            model_name='run',
            name='run_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsi.RunBase'),
        ),
        migrations.AddField(
            model_name='run',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
